// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxiLm35_4d-1cg-Rq6LDaXvjwRRvm1SUQ',
    appId: '1:528855485063:web:9c9a9ae511907464574622',
    messagingSenderId: '528855485063',
    projectId: 'engineer-fa08b',
    authDomain: 'engineer-fa08b.firebaseapp.com',
    storageBucket: 'engineer-fa08b.firebasestorage.app',
    measurementId: 'G-2CMK74EM8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwkC7roEXqXiLw3VJmToeXiB9U309YMRA',
    appId: '1:528855485063:android:3f929ab97462428e574622',
    messagingSenderId: '528855485063',
    projectId: 'engineer-fa08b',
    storageBucket: 'engineer-fa08b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoc-1q15WgLNsJ0TobGLgtuJ63ess64wk',
    appId: '1:528855485063:ios:29d7d53879224c9a574622',
    messagingSenderId: '528855485063',
    projectId: 'engineer-fa08b',
    storageBucket: 'engineer-fa08b.firebasestorage.app',
    androidClientId: '528855485063-c9s095cs2odjn9coqc415pbb9slqm6b2.apps.googleusercontent.com',
    iosClientId: '528855485063-nvmohi28mbqiak1r6a8m22b95dkt3h0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxiLm35_4d-1cg-Rq6LDaXvjwRRvm1SUQ',
    appId: '1:528855485063:web:d7a824fde833f73b574622',
    messagingSenderId: '528855485063',
    projectId: 'engineer-fa08b',
    authDomain: 'engineer-fa08b.firebaseapp.com',
    storageBucket: 'engineer-fa08b.firebasestorage.app',
    measurementId: 'G-4KW0JQ6LMJ',
  );
}
